config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :users
  root to: "messages#index"
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/default_order.rb
module DefaultOrder
  extend ActiveSupport::Concern

  included do
    scope :trashed, -> { where(trashed: true) }
  end
end

app/models/message.rb
class Message < ApplicationRecord
  include DefaultOrder
  validates :name, :entry, :ip_address, presence: true
  scope :by_ip_address, ->(ip) { where(ip_address: ip) }

  # belongs_to :user, class_name: "user", foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages

  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper

  private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, :logged_in_user, only: [:show, :edit, :update, :destroy]
  # GET /messages
  # GET /messages.json
  def index
    
    if logged_in?
    if params[:filter].blank?
      @messages = Message.order("created_at DESC")
      # p @messages
    else
      my_ip = request.remote_ip
      @messages = Message.by_ip_address(my_ip).all
    end
  else
    if params[:filter].blank?
      @messages = Message.where(hidden: false).order("created_at DESC")
      # p @messages
    else
      my_ip = request.remote_ip
      @messages = Message.where(hidden: false).by_ip_address(my_ip).all
    end
  end
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.ip_address = request.remote_ip

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @message.hidden = params[:hidden]
    # p @message.errors.messages
    if @message.save
      redirect_to messages_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def by_ip_address (ip)
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:name, :entry, :ip_address, :hidden)
    end

    def update_message_params
      params.require(:message).permit(:hidden)
    end    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
                .try(:authenticate, params[:session][:password])
    
    if user
      log_in user
      redirect_to messages_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # p @user
      log_in @user
      flash[:success] = "Welcome to the app!"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    # p session[:user_id]
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Rails Guest</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application' , 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Your Name' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :entry, 'Your Message' %>
    <%= form.text_area :entry, rows: 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_nav.html.erb
<div>
    <hr />
    <a href="<%= messages_path %>">All Messages</a> |
    <a href="<%= messages_path(filter: 'me') %>">My Messages</a> |
    <strong><a class="btn btn-primary" href="<%= new_message_path %>" role="button">Add a Message</a></strong> |
    <% if logged_in? %>
    <%= link_to "Log out", logout_path, method: :delete %>
    <p>Logged User: <%= current_user.name %></p>
    <% else %>
    <a href="<%= login_path %>">Log in</a> |
    <a href="<%= signup_path %>">Sign up</a>
    <% end %>
</div>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<%= render 'nav' %>

<% @messages.each do |message| %>
  <div class="card-body <% if logged_in? and message.hidden %>text-red<% end %>">
    <hr />
    <p class="card-text"><%= message.entry %></p>
    <p class="card-text">
        <small class="text-muted">
            <span class="text-muted">Added <%= message.created_at.to_s(:short) %> by <%= message.name %></span>
        </small>
    </p>

    <p>
    <% if logged_in? %>
    <% if message.hidden %>
        <%= link_to "Show", message_path(:id => message.id, :hidden => false), class: "mx-2", method: :patch %>
    <% else %>
        <%= link_to "Hide", message_path(:id => message.id, :hidden => true), class: "mx-2", method: :patch %>
    <% end %>
    <% end %>
    </p>

  </div>
<% end %>


app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/users/new.html.erb
<h1 class='text-center'>Sign up</h1>

<div class="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'mb-1 form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'mb-1 form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'mb-1 form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'mb-1 form-control' %>

  <div class="actions">
      <%= f.submit "Create my account", class: "mt-2 btn btn-primary" %>
  </div>      
    <% end %>
  </div>
</div>

<%= link_to 'Back', messages_path %>